const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
};

const USER = {
  LOAD: 'USER_LOAD',
  LOAD_SUCCESS: 'USER_LOAD_SUCCESS',
  LOAD_FAIL: 'USER_LOAD_FAIL',
  CREATE: 'USERS_CREATE',
  UPDATE: 'USERS_CREATE',
  CREATE_SUCCESS: 'USERS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
  CREATE_FAIL: 'USERS_CREATE_FAIL',
  UPDATE_FAIL: 'USERS_UPDATE_FAIL',
};

export { USERS, USER };
